"""Typed agent-graph model, loading, validation, and session identity."""

from .domain_values import DomainValues
from .loader import (
    entry_to_dict,
    get_agent_emoji,
    graph_config_sha,
    load_agent_graph,
    load_publisher_name,
    record_to_entry,
)
from .meta import validate_config_document, validate_config_meta
from .model import (
    Configuration,
    ConsolidationSpec,
    Edge,
    FanOut,
    GraphEntry,
    McpBinding,
    PowershellToolPolicy,
    PublishingPolicy,
    ReadPowershellToolPolicy,
    ToolPolicy,
    find_dep_cycle,
    finding_producing_agent_keys,
    get_configuration,
    get_entry,
    get_product_emoji,
    get_product_name,
    get_report_title,
    register_config_plugins,
    validate_graph_config,
)
from .predicates import (
    Predicate,
    evaluate_predicate,
    parse_predicate,
    predicate_to_dict,
)
from .session_identity import (
    ConfigurationIdentity,
    ConfigurationIdentityError,
    describe_active_configuration,
    fingerprint_drift,
    require_compatible_fingerprint,
    resolve_session_configuration,
)

__all__ = [
    "Configuration",
    "ConfigurationIdentity",
    "ConfigurationIdentityError",
    "ConsolidationSpec",
    "DomainValues",
    "Edge",
    "FanOut",
    "GraphEntry",
    "McpBinding",
    "PowershellToolPolicy",
    "Predicate",
    "PublishingPolicy",
    "ReadPowershellToolPolicy",
    "ToolPolicy",
    "describe_active_configuration",
    "entry_to_dict",
    "evaluate_predicate",
    "find_dep_cycle",
    "finding_producing_agent_keys",
    "fingerprint_drift",
    "get_agent_emoji",
    "get_configuration",
    "get_entry",
    "get_product_emoji",
    "get_product_name",
    "get_report_title",
    "graph_config_sha",
    "load_agent_graph",
    "load_publisher_name",
    "parse_predicate",
    "predicate_to_dict",
    "record_to_entry",
    "register_config_plugins",
    "require_compatible_fingerprint",
    "resolve_session_configuration",
    "validate_config_document",
    "validate_config_meta",
    "validate_graph_config",
]
