"""Typed backend execution contract and registered implementations."""

from .mock_runner import MockBackend, build_valid_stub, make_mock_run_agent, mock_backend
from .outcome import BackendOutcome
from .registry import (
    Backend,
    BackendCapabilities,
    BackendCapabilityResolver,
    BackendOptions,
    BackendProvider,
    FunctionBackend,
    KeywordBackend,
    backend_capabilities,
    backend_context,
    backend_provider,
    normalize_backend_result,
    open_backend,
    register_backend,
)
from .result import (
    DEFAULT_RETENTION_POLICY,
    SUBMISSION_TOOL_NAME,
    CopilotResult,
    ExecutionPolicy,
    OutputSubmission,
    RetentionPolicy,
    RunRequest,
    RunResult,
    SubmissionAttempt,
    SubmissionResult,
    SubmissionValidation,
    retain_submission_diagnostics,
)
from .sdk import SdkBridge, TurnResult, require_sdk, resolve_auth, sdk_versions
from .sdk_runner import SdkBackend, make_sdk_run_agent, sdk_backend
from .usage import (
    EMPTY_USAGE,
    NOT_APPLICABLE_BILLING,
    SDK_BILLING_SOURCE,
    SDK_BILLING_WARNING,
    AgentUsage,
    BillingStatus,
    BillingValue,
    anomalous_finish_reasons,
    as_float,
    format_ai_credits,
    merge_usage,
)

register_backend(
    "copilot",
    sdk_backend,
    lambda: BackendCapabilities(cancellation=True, cost=True, provider_tool_policy=True),
)
register_backend("mock", mock_backend, lambda: BackendCapabilities(tools=False))

__all__ = [
    "DEFAULT_RETENTION_POLICY",
    "EMPTY_USAGE",
    "NOT_APPLICABLE_BILLING",
    "SDK_BILLING_SOURCE",
    "SDK_BILLING_WARNING",
    "SUBMISSION_TOOL_NAME",
    "AgentUsage",
    "Backend",
    "BackendCapabilities",
    "BackendCapabilityResolver",
    "BackendOptions",
    "BackendOutcome",
    "BackendProvider",
    "BillingStatus",
    "BillingValue",
    "CopilotResult",
    "ExecutionPolicy",
    "FunctionBackend",
    "KeywordBackend",
    "MockBackend",
    "OutputSubmission",
    "RetentionPolicy",
    "RunRequest",
    "RunResult",
    "SdkBackend",
    "SdkBridge",
    "SubmissionAttempt",
    "SubmissionResult",
    "SubmissionValidation",
    "TurnResult",
    "anomalous_finish_reasons",
    "as_float",
    "backend_capabilities",
    "backend_context",
    "backend_provider",
    "build_valid_stub",
    "format_ai_credits",
    "make_mock_run_agent",
    "make_sdk_run_agent",
    "merge_usage",
    "normalize_backend_result",
    "open_backend",
    "register_backend",
    "require_sdk",
    "resolve_auth",
    "retain_submission_diagnostics",
    "sdk_backend",
    "sdk_versions",
]
